#springdoc:
#  swagger-ui:
#    urls:
#      # Les URLs seront configur√©es dynamiquement
#    disable-swagger-default-url: true
#  api-docs:
#    enabled: true

#springdoc:
#  swagger-ui:
#    path: /swagger-ui.html
#    disable-swagger-default-url: true
#    urls: []
#  api-docs:
#    path: /v3/api-docs
#    enabled: true


springdoc:
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha
    # Activer le mode "try it out" pour tous les endpoints
    try-it-out-enabled: true
  api-docs:
    path: /v3/api-docs
    enabled: true